;/*FB_PKG_DELIM*/

__d("CometIXTFacebookContentTriggerRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5931494706897560"}),null);
__d("CometIXTFacebookContentTriggerRootQuery$Parameters",["CometIXTFacebookContentTriggerRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometIXTFacebookContentTriggerRootQuery_facebookRelayOperation"),metadata:{},name:"CometIXTFacebookContentTriggerRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometIXTFacebookContentTriggerEntryPoint.entrypoint",["CometIXTFacebookContentTriggerRootQuery$Parameters","JSResourceForInteraction","React","WebPixelRatio","uuid"],(function(a,b,c,d,e,f,g){"use strict";c("React");a={getPreloadProps:function(a){return{queries:{reference:{parameters:c("CometIXTFacebookContentTriggerRootQuery$Parameters"),variables:{input:babelHelpers["extends"]({},a,{nt_context:null,trigger_session_id:c("uuid")()}),scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("CometIXTFacebookContentTriggerRoot.react").__setRef("CometIXTFacebookContentTriggerEntryPoint.entrypoint")};b=a;g["default"]=b}),98);
__d("useIXTContentTriggerDialog",["cr:2988","cr:3116"],(function(a,b,c,d,e,f,g){"use strict";function a(a){return b("cr:3116")(b("cr:2988"),a)}g["default"]=a}),98);
__d("cometReportBugDefaultOptions",["fbt","ix","fbicon"],(function(a,b,c,d,e,f,g,h,i){"use strict";a="public";b=h._("__JHASH__Sqzl58OucnB__JHASH__");c={addOnPrimary:{icon:d("fbicon")._(i("899558"),24),size:60,type:"contained-icon"},body:h._("__JHASH__5q7igOED7sX__JHASH__"),dialogTitle:h._("__JHASH__OPf0ZWrh9kh__JHASH__"),headline:h._("__JHASH__mBwCXx86-aM__JHASH__")};e={addOnPrimary:{icon:d("fbicon")._(i("502063"),24),size:60,type:"contained-icon"},body:h._("__JHASH__T0wDs12oUvR__JHASH__"),dialogTitle:h._("__JHASH__d8pLVqIL7yK__JHASH__"),headline:h._("__JHASH__06damxz0Ivb__JHASH__")};g.defaultProductListType=a;g.defaultInitialTitle=b;g.defaultFeedbackProblemTypeItem=c;g.defaultBugProblemTypeItem=e}),98);
__d("useCometReportBug",["fbt","CometCardedDialogLoadingStateLegacy.react","JSResourceForInteraction","cometReportBugDefaultOptions","promiseDone","react","useCometLazyDialog"],(function(a,b,c,d,e,f,g,h){"use strict";b=d("react");var i=c("react"),j=b.useCallback,k=b.useRef,l=c("JSResourceForInteraction")("CometBugReportingDialog.react").__setRef("useCometReportBug"),m=c("JSResourceForInteraction")("VideoPlayerShakaPerformanceLogger").__setRef("useCometReportBug"),n=!1;function a(a){var b=k(null),e=c("useCometLazyDialog")(l,function(b){return i.jsx(c("CometCardedDialogLoadingStateLegacy.react"),{onClose:b,title:a==null?h._("__JHASH__Sqzl58OucnB__JHASH__"):h._("__JHASH___hkwAd2dM-2__JHASH__",[h._param("product name",a)]),withCloseButton:!0})}),f=e[0];e=j(function(b,e){if(!n){var g;c("promiseDone")(m.load().then(function(a){a.flushQueuedLogs()}));f(babelHelpers["extends"]({productName:a},b,{bugProblemTypeItem:(g=b==null?void 0:b.bugProblemTypeItem)!=null?g:d("cometReportBugDefaultOptions").defaultBugProblemTypeItem,feedbackProblemTypeItem:(g=b==null?void 0:b.feedbackProblemTypeItem)!=null?g:d("cometReportBugDefaultOptions").defaultFeedbackProblemTypeItem,initialTitle:(g=b==null?void 0:b.initialTitle)!=null?g:d("cometReportBugDefaultOptions").defaultInitialTitle,productListType:(g=b==null?void 0:b.productListType)!=null?g:d("cometReportBugDefaultOptions").defaultProductListType}),function(){e!=null&&e(),n=!1});n=!0}},[f]);return[e,b]}g["default"]=a}),98);
__d("useLaunchFRXFlow",["react","useIXTContentTriggerDialog"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useRef;function a(a){var b=h(null);a=c("useIXTContentTriggerDialog")(a);var d=a[0],e=a[1],f=a[2];a=a[3];return[d,b,e,f,a]}g["default"]=a}),98);
__d("WarningScreenRenderType",[],(function(a,b,c,d,e,f){a=Object.freeze({GEOBLOCK:"GEOBLOCK",FULL_COVER:"FULL_COVER",LIGHTWEIGHT:"LIGHTWEIGHT",POST_COVER:"POST_COVER"});f["default"]=a}),66);