;/*FB_PKG_DELIM*/

__d("CometCreationContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext({isDraft:!1});g["default"]=b}),98);
__d("useIsCreationPreview",["CometCreationContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useContext;function a(){var a=h(c("CometCreationContext"));return a.isDraft}g["default"]=a}),98);
__d("NullStateLists",["cr:3212"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:3212")}),98);
__d("NullStateListsFB",["IconSource"],(function(a,b,c,d,e,f,g){"use strict";a={dark:new(c("IconSource"))("nullStateGlyphs","/images/comet/empty_states_icons/lists/null_states_list_dark_mode.svg",112),"default":new(c("IconSource"))("nullStateGlyphs","/images/comet/empty_states_icons/lists/null_states_list_gray_wash.svg",112)};g["default"]=a}),98);
__d("createUseMutation_DEPRECATED",["CometRelay","Promise","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useCallback;function a(a,c,e,f){return function(){var g=d("CometRelay").useRelayEnvironment();return h(function(h,i,j){return new(b("Promise"))(function(b,k){return d("CometRelay").enqueueMutation(g,{mutation:a,onCompleted:function(a,c){c&&c.length?k(c):b(a)},onError:function(a){return k([a])},optimisticResponse:c?c(h,i,j):null,optimisticUpdater:e?e(h,i,j):null,updater:f?f(h,i,j):null,variables:babelHelpers["extends"]({input:h},i)})})},[g])}}g["default"]=a}),98);
__d("GroupsKeyCommandShortcutsFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2955");b=d("FalcoLoggerInternal").create("groups_key_command_shortcuts",a);e=b;g["default"]=e}),98);
__d("CometEntityScopedTypeaheadDialogTrigger.react",["fbt","ix","CometKeys","GroupsKeyCommandShortcutsFalcoEvent","TetraButton.react","fbicon","react","useLayerKeyCommands","useSearchCometResultsTypeaheadDialogTriggerClickHandler"],(function(a,b,c,d,e,f,g,h,i){"use strict";var j=d("react"),k=d("react").useMemo;function a(a){var b=a.buttonProps,e=a.dialogEntryPoint,f=a.entityID;a=a.entityType;e=c("useSearchCometResultsTypeaheadDialogTriggerClickHandler")(e,f,a);var g=e[0];a=e[1];var l=e[2],m=e[3];e=e[4];var n=k(function(){return[{command:{command:!0,key:c("CometKeys").SLASH},description:h._("__JHASH__91WBOQfbx5z__JHASH__"),handler:function(){c("GroupsKeyCommandShortcutsFalcoEvent").log(function(){return{event:"open_group_scoped_search",group_id:f}}),g()}}]},[g,f]);c("useLayerKeyCommands")(n);return j.jsx(c("TetraButton.react"),babelHelpers["extends"]({icon:d("fbicon")._(i("491282"),16),label:h._("__JHASH__1auhn96MH3g__JHASH__"),labelIsHidden:!0,onHoverIn:l,onHoverOut:m,onPress:g,onPressIn:e,ref:a,testid:void 0,type:"secondary"},b))}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("CometComposerPushedPageOnLoad",[],(function(a,b,c,d,e,f){a=Object.freeze({ASK_FOR_RECOMMENDATIONS:"ask_for_recommendations",ASK_ME_ANYTHING:"ask_me_anything",COMMUNITY_QA:"community_qa",CONNECT_WHATSAPP:"connect_whatsapp",FEELING:"feeling",FUNDRAISER:"fundraiser",GET_MESSAGES:"get_messages",GET_WHATSAPP_MESSAGES:"get_whatsapp_messages",LOCAL_ALERT_TAGGER:"local_alert_tagger",LOCATION_TAGGER:"location_tagger",LOOKING_FOR_PLAYERS:"looking_for_players",MLE:"mle",PHOTO_VIDEO:"photo_video",PRAYER:"prayer",PRODUCT_TAGGER:"product_tagger",QUILTS_COMPOSER:"quilts_composer",SHARE_CANDIDATE:"share_candidate",SHIFT_COVER:"shift_cover",SHIFT_MANAGEMENT_COVER:"shift_management_cover",VIDEO_MEETUP:"video_meetup",VIDEO_PICKER:"video_picker",VOTING_ALERT_TAGGER:"voting_alert_tagger",WITH_TAGGER:"with_tagger"});f["default"]=a}),66);